name: Build and Release SDKs

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write


jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SDK repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

    #   - name: Set up Swift
    #     uses: swift-actions/setup-swift@v3

      - name: Build Python package
        run: |
          cd python
          python -m pip install --upgrade build setuptools wheel
          python -m build --sdist --wheel
          ls -lh dist

    #   - name: Build Swift SDK
    #     run: |
    #       cd swift6
    #       swift build -c release

      - name: Upload Python SDK packages
        uses: softprops/action-gh-release@v2
        with:
            files: python/dist/*
            tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   - name: Upload Swift SDK
    #     uses: softprops/action-gh-release@v2
    #     with:
    #       files: swift6/build/release/*
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

